### ISSUE TITLE
Port cel2pnm to Haskell

### ISSUE THREAD

**Issue by huggablemonad** [emhoracek/smooch#41]
Hi @emhoracek, would it still be useful to port the palette parsing code to Haskell from cel2pnm? Or do you prefer that it be done in JavaScript? I'm slightly confused because the roadmap mentions "inlining the C code," which I assumed was to be done in Haskell, but CONTRIBUTING.md suggests "moving the palette parsing into JavaScript."

**Comment by emhoracek** [comment]
Hi @huggablemonad thanks for asking. The roadmap is still pretty fuzzy. The key thing is not having a separate C script that has to be installed -- whether that happens in Haskell or JavaScript basically depends on which we can get working in an efficient manner. 

I already started a JavaScript implementation [here](https://github.com/emhoracek/smooch/blob/master/javascript/reader.html) and [here](https://github.com/emhoracek/smooch/blob/master/javascript/reader.js) but since the frontend of Smooch is already dreadfully slow I'm not going to actually use it just yet. 

Currently I'm focusing on getting the web app ready for deployment, but If you would be interested in working on using Haskell, whether inlining the C or using pure Haskell, I would 100% support that. I think it could be a really fun project!

**Comment by huggablemonad** [comment]
@emhoracek Could you help shed some light on what palette groups are (in the header of a `KCF` file)? I think it allows for multiple palettes in a single `KCF` file, like `bg1.kcf`, `bg2.kcf`, etc. in one `background.kcf`, but maybe that's not what it means? The [Set Information](https://github.com/emhoracek/smooch/wiki/The-first-KiSS-Specification#set-information) section for `CNF` files mentions palette groups, but they don't seem to be talking about quite the same thing.

**Comment by emhoracek** [comment]
@huggablemonad That's a really good question. Palette groups were used more in early KiSS sets than during the time when I learned to make them. So, I don't really understand them either. I wonder if they are related to the problems with #14 and #10. If I were working on this, I'd look at what [Gnome KiSS](http://devel.tlrmx.org/kiss/) does with them, maybe find some early sets from OtakuWorld that use them and take a look at the palettes/cels?

**Comment by huggablemonad** [comment]
@emhoracek Thanks for the hint! I found a set from 1993, [Erika, Shinobu, Hiromi](https://otakuworld.com/kiss/dolls/pages/k/kiss_eri.htm), that uses palette groups. The next step is probably to figure out how to implement support for them, maybe in a separate issue?

As for converting cels to PNGs, I think it's possible to replace `pnmtopng` with [`JuicyPixels`](https://hackage.haskell.org/package/JuicyPixels).

![washu-pnmtopng](https://user-images.githubusercontent.com/17948023/31613877-045471f6-b2b7-11e7-8e7c-a22823ed9de0.png)![washu-juicypixels](https://user-images.githubusercontent.com/17948023/31613888-09d308ae-b2b7-11e7-9753-5a1c3ea299b6.png)

The image on the left was created with `pnmtopng`, and the one on the right with `JuicyPixels`. The difference between the two seems to be that the former is a paletted PNG, whereas the latter is an RGBA PNG. `JuicyPixels` [lacks support for RGBA palettes in PNGs](https://github.com/Twinside/Juicy.Pixels/issues/138) -- that's why I had to convert the cel to an RGBA format.

Do you think it would be beneficial to switch to `JuicyPixels`, or should we stick with `pnmtopng` for now?

**Comment by emhoracek** [comment]
@huggablemonad There is a size difference -- the paletted PNG is 3.34KB and the unpaletted is 5.6KB. Given that each image has to be downloaded over the network, this could feel very significant for large sets. 2KB additional x 250 cels = half a MB! However maybe we could use regular PNG for now and eventually I'll offer a small bounty for someone to add palette support to JuicyPixels. ^_^

Does JuicyPixels require any non-Haskell libraries, like ImageMagick or something? Just trying to evaluate how this will impact ease of installation for new contributors.

**Comment by huggablemonad** [comment]
@emhoracek That's a good point regarding the increased download size. Are you planning to deploy Smooch to AWS?

JuicyPixels doesn't depend on any non-Haskell libraries. It's all pure Haskell, as far as I can tell. Should I add pnm output like cel2pnm does, so you can better evaluate the trade-offs?

**Comment by emhoracek** [comment]
I am planning on deploying to AWS and using s3 eventually but this matters regardless of where the server is located, since the end user's browser is going to be downloading all the images no matter what. If someone is on a mobile phone plan, a MB is a small but significant difference. 

However, since Smooch doesn't even work now on mobile, this tradeoff seems very worth it!  *Especially*  if you can avoid the PNM step. Please don't bring that back. 😂

**Comment by huggablemonad** [comment]
Hmm... it looks like the PNM step might be sticking around for a little longer than anticipated. The Haskell port works, but is horrendously slow. It takes 3 times as long to convert all 167 cels in 
the Arwen set as compared to `cel2pnm` + `pnmtopng`! :scream: There's a bit more detail in the pull request (#50).

**Comment by Twinside** [comment]
I could take the bounty for the JuicyPixel ticket :]

**Comment by emhoracek** [comment]
@Twinside tbh I have no idea what is an appropriate amount for such a thing but I'll definitely donate to JuicyPixels if Smooch ends up using it (regardless of the palette issue). It seems really nice and it looks like @huggablemonad figured out the performance issues.

**Comment by Twinside** [comment]
Around the price of a steam game would be nice ;)
