### ISSUE TITLE
Log user in and redirect to user page on account creation

### ISSUE THREAD

**Issue by jarmstrng** [emhoracek/smooch#69]
What is the current behavior?
currently, displays "created". must go back and log in with new account

What is the expected behavior?
Log user in and redirect to user page on account creation

**Comment by huggablemonad** [comment]
Hi @emhoracek, this seems straightforward to implement, so do you want to maybe leave it for Hacktoberfest or something?

**Comment by emhoracek** [comment]
@huggablemonad Yeah, the only reason it isn't done already is that I'm currently focusing on the stuff I need to do to get the app deployable -- integrating your cel processing code, putting the files on s3 instead of serving locally, etc. If you want to do it, go for it, or it can wait till Hacktober.
