### ISSUE TITLE
Handle Japanese encodings

### ISSUE THREAD

**Issue by emhoracek** [emhoracek/smooch#9]
Right now the viewer crashes on SHIFT_JIS-encoded configuration files.

This means none of the oldest dolls work. :(

 Example: sk_kimux.lzh

**Comment by ear** [comment]
I made some discoveries as soon as the stream was off:

All of the various utilities that interact with `icu` stuff one way or another work differently depending on the `locale -a` environment variables. Setting `LANG=C` and `LC_CTYPE=C` made `file` start not to break anymore!

Now your repeated application test is recognizable 😄 

```
$ export LANG=C LC_CTYPE=C
$ ./Main kiss.cnf > kiss.cnd.utf8
$ ./Main kiss.cnf.utf8 > kiss.cnf.utf8.utf8
$ file kiss.cnf
kiss.cnf: Non-ISO extended-ASCII text, with CRLF, NEL line terminators
$ file kiss.cnf.utf8
kiss.cnf.utf8: UTF-8 Unicode text, with CRLF, LF line terminators
$ file kiss.cnf.utf8.utf8
kiss.cnf.utf8.utf8: data
```

The program is [here](https://gist.github.com/ear/7dd6c4d045f05ebad9f923b671c370b2).

**Comment by emhoracek** [comment]
Interesting! Maybe use `setLocaleEncoding <something>` in the script? Maybe `setLocaleEncoding (mkTextEncoding "C")`? (Trying to think of ways to avoiding messing with my environment)

**Comment by emhoracek** [comment]
<img width="451" alt="screen shot 2017-08-13 at 9 48 29 pm" src="https://user-images.githubusercontent.com/5353499/29255629-338e5d38-8071-11e7-9d09-872eca916669.png">

hey look!

I'm still not satisfied that I understand this problem well enough to figure out the best solution, so I'm going to do a bit more studying before I actually commit to this -- but Smooch can read a Japanese set! :D

**Comment by emhoracek** [comment]
Thanks for your help @ear! Here's a set: http://emhoracek.github.io/smooch/example-sets/sk_kimux/ and the code that made it happen ^__^ https://github.com/emhoracek/smooch/blob/master/haskell/src/Upload.hs#L103

**Comment by ear** [comment]
That's great! I wonder why the argument needs to be forced in [`return $! T.decodeUtf8 fileBS`](https://github.com/emhoracek/smooch/blob/master/haskell/src/Upload.hs#L109). I don't have much experience with `catch` actually.

I wonder can you explain the reason behind the pervasive use of `EitherT`? I'm genuinely curious.

**Comment by emhoracek** [comment]
@ear Both very good questions!

The `decodeUtf8` needs to be forced because otherwise the error occurs "outside" the `catch` and doesn't get handled. Due to laziness, the error doesn't happen until the app actually starts looking at the text.

The pervasive use of `EitherT` is because I wanted a consistent interface for handling failures, since things can fail all over the place. Shell commands can fail, parsers can fail, etc. I think if I were designing this today, I would make more use of exceptions and exception handling because I'm more comfortable with that now. But at the time it was a good way to make sure I always had a helpful error message to display to the user as well as a good way to learn monad transformers.

**Comment by ear** [comment]
@emhoracek thank you for the fast reply. Funny how exceptions can escape a catch because of laziness! It makes sense.

I'm also impressed by the idea of using exceptions more. I never liked them in other languages because of the impact they have on control flow. They usually make it harder to reason about code because you need to take in consideration control flow points that might be far away from the code you're reading. I think I never used them in Haskell now that I think about it!

I think I was wondering what's the operational difference between `EitherT Foo IO a` and `IO (Either Foo a)` that made you choose the former. Here I don't have an agenda, I'm just curious :smile:

**Comment by ear** [comment]
OH yours is a very good point. Those two types *are* the same.

- If you use `IO (Either e a)` you have to unwrap Eithers by hand
- If you use `EitherT a IO a` do-notation does it for you

I like how this is not magical but very explicit: I'm looking at `bind`'s definition with this new pair of glasses you gave me 🤓

```haskell
instance Monad m => Monad (EitherT e m) where
  return a = EitherT $ return (Right a)
  m >>= k  = EitherT $ do
    a <- runEitherT m
    case a of
      Left  l -> return (Left l)
      Right r -> runEitherT (k r)
```

This is very nice so I looked into where you use this monad and found [these](https://github.com/emhoracek/smooch/blob/master/haskell/src/Web.hs#L64) [examples](https://github.com/emhoracek/smooch/blob/master/haskell/src/Web.hs#L70). It struck me that  `liftIO` is actually just `id` in `IO a` in those two places. Is that right? I think they might be not needed at all.

I got interested in [`tryIO`](https://github.com/emhoracek/smooch/blob/master/haskell/src/Upload.hs#L90-L95) too. I hope you don't mind. I understand if it was just meant for the uses inside the module and you don't care at all about the things I'm about to say but I found them interesting, especially because they actually work, which I was super unsure about to start with 😄 

For starters I found a couple helper functions in `Control.Monad.Trans.Either` that make the code prettier:

```haskell
tryIO :: IO () -> EitherT Text IO ()
tryIO m = do
  res <- liftIO (try m :: IO (Either IOException ()))
  case res of
    Right () -> right ()
    Left e   -> left (T.pack $ show e)
```

That type signature on `try m` made me wonder: we're relying on `try` to catch the exception and make it an `Either`. Thus this function really only does this:

```haskell
Either IOException () -> Either Text ()
```

Then it lifts the `IO (Either Text ())` to our monad `EitherT Text IO ()`. Which is exactly the `EitherT` constructor. Here is what I came up with:

```haskell
tryIO :: IO a -> EitherT Text IO a
tryIO m = EitherT $ mapLeft showIOException <$> try m
  where
    showIOException = T.pack . show :: IOException -> Text
```

Funnily enough I also had a stray `liftIO` in there while editing this message! Haha I'm really seeing how these things can linger around. `mapLeft` comes from `Data.Either.Combinators` also defined in the `either` package. I also made the type more general so that more useful IO actions can be tryIO-ed.

Truthfully I was doubtful this was actually going to work. I would really have been fine with discovering I was missing something substantial about exceptions. These tests seem to work exactly like your implementation and convinced me to write down this comment:

```haskell
λ> runEitherT $ tryIO $ putStrLn "hello" >> readFile "./Main.hs" >>= \xs -> putStrLn "world" >> return (length xs)
hello
world
Right 1399

λ> runEitherT $ tryIO $ putStrLn "hello" >> readFile "./meepmeep" >>= \xs -> putStrLn "world" >> return (length xs)
hello
Left "./meepmeep: openFile: does not exist (No such file or directory)"

```

This might actually be fine!

I hope I'm not missing the point completely. It could be that lifting all of your computations into `EitherT e IO a` is a good design idea. In the sense that you are then freer to move code around in your module(s) and it's all compatible. On the other hand I'm also pleased that the code I came up with is both compact and not dense nor opaque (I think!)

Thanks for the engaging discussion, this is quite fun! 🍸 ✨

**Comment by emhoracek** [comment]
Hi @ear, those refactorings look very nice to me! When I wrote most of the EitherT code I was still very new to monad transformers and didn't understand them very well at all. I had a tendency to use `liftIO` as a sort of magic word to make stuff work. :joy: You're right that of course `liftIO` isn't necessary in those two examples -- maybe other places too. I also like these helper functions you found! Would you be interested in applying some of these refactors and opening a PR? I think it could improve the codebase a lot.

**Comment by ear** [comment]
I just came across something that I had no idea existed—it seems obvious it has to exist, in hindsight: http://hackage.haskell.org/package/charsetdetect-ae
